version: "3.8"

volumes:
  db_data:

services:
#  app:
#    image: helloapi:latest
#    build:
#      context: .
#    environment:
#      <<: *shared_environment
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"

  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
      MYSQL_DATABASE: vapor_database
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - "3310:3306"
